src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Aporta_ingresos__c</fullName>
        <label>Aporta ingresos</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Codeudores</relationshipLabel>
        <relationshipName>Codeudores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valida_aporta_ingresos__c</fullName>
        <label>Valida aporta ingresos</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountUpdateField_cls.cls
public class AccountUpdateField_cls 
{
    
    //public static void setAccountUpdate(List<Account> lstAcc)
    //{
        
    //    //System.debug('Debuline 11: lstAccsize: '+lstAcc.size()+', lstAcc: '+lstAcc);
    //    List<Account> lstcodeudores= new List<Account>();
    //    Set<String> stIds= new Set<String>();
    //    Map<String,Account> mpAcc= new Map<String,Account>();
    //    for(Account objAccount:lstAcc)
    //    {
    //        mpAcc.put(objAccount.Id,objAccount);
    //    }
    //    for(Account objAccount:lstAcc)
    //    {
    //    	//System.debug('1');
    //        //System.debug('RecordType: ' + Label.AccountRecordTypeId);
    //        if(objAccount.RecordTypeId==Label.AccountRecordTypeId && !stIds.contains(objAccount.Cliente_deudor__c))
    //        {
    //    		//System.debug('3');
    //            stIds.add(objAccount.Cliente_deudor__c);
    //            if(!mpAcc.containsKey(objAccount.Cliente_deudor__c))
    //            {
		  //      	//System.debug('4');
    //                Account objAcc= new Account(Id=objAccount.Cliente_deudor__c,Valida_aporta_ingresos__c=objAccount.Aporta_ingresos__c);
    //                lstcodeudores.add(objAcc);
    //            }
    //        }
    //    }
    //    //System.debug('Debuline 24: lstcodeudores: '+lstcodeudores);
    //    //if(lstcodeudores.size() > 0){
    //    //    upsert lstcodeudores;
    //    //}
    //}
    
}