src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Codeudores</relationshipLabel>
        <relationshipName>Codeudores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <externalId>true</externalId>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Codeudor__c.object
<CustomObject>
    <description>Estará inicialmente relacionado con el Candidato y en el reposará la información correspondiente a los Codeudores.</description>
    <fields>
        <fullName>Apellidos__c</fullName>
        <label>Apellidos</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidato</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Solicitantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <label>Número de documento</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Codeudor</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codeudores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
	
	public static Id createLead() {
		Lead lead = new Lead();
		insert lead;
		return lead.Id;
	}
	
	public static Id createCodeudor(Id leadId, Integer numeroDeDocumento) {
		Codeudor__c cod = new Codeudor__c(
			Name = 'CodeudorTest',
			Apellidos__c = 'Test',
			Candidato__c = leadId,
			Numero_de_documento__c = numeroDeDocumento
		); 
		insert cod;
		return cod.Id;
	}

	public static Id createAccount(Id recordTypeId){
		Account acc = new Account(
			RecordTypeId = recordTypeId,
			LastName = 'TestLastname',
            FirstName = 'TestName',
			Numero_de_documento__c = String.valueOf(Crypto.getRandomInteger()) 
		);
		return acc.Id;
	}

	public static Id createAccount(Id recordTypeId, Id clienteDeudorId){
		Account acc = new Account(
			RecordTypeId = recordTypeId,
			Cliente_deudor__c = clienteDeudorId,
			LastName = 'TestLastname',
            FirstName = 'TestName',
			Numero_de_documento__c = String.valueOf(randomWithLimit(1000000000))
		);
		return acc.Id;
	}

	public static Integer randomWithLimit(Integer upperLimit){
        Integer rand = Math.round(Math.random()*1000);
        return Math.mod(rand, upperLimit);
    }
	
}