src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Codeudores</relationshipLabel>
        <relationshipName>Codeudores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <externalId>true</externalId>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Numero_de_telefono_celular__c</fullName>
        <label>Número de celular</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validar_numero_de_celular__c</fullName>
        <label>Validar número de celular</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validar_numero_de_documento__c</fullName>
        <label>Validar número de documento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Actualizacion_masiva_de_registros__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Actualizará los objetos Información financiera, información comité y Referenciación y verificación desde la Radicación y se actualizará el objeto paz y salvo desde la solicitud de crédito</description>
    <fields>
        <fullName>Campo_Id__c</fullName>
        <label>Campo Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Actualización masiva de registros</label>
</CustomObject>

src/objects/Informacion_comite__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Información comité</relationshipLabel>
        <relationshipName>Informacion_comite</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Información comité (Codeudor 1)</relationshipLabel>
        <relationshipName>Informaci_n_comit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Información comité (Codeudor 2)</relationshipLabel>
        <relationshipName>Informacion_comite1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Información comité (Codeudor 3)</relationshipLabel>
        <relationshipName>Informacion_comite3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Radicacion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipLabel>Información comité</relationshipLabel>
        <relationshipName>Informacion_comite</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Informacion_comite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Información comité</label>
        <referenceTo>Informacion_comite__c</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Telefono_oficina__c</fullName>
        <label>Teléfono oficina</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_familiar__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_personal__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/InformacionComite_tst.cls
@isTest
private class InformacionComite_tst 
{

    
    static testMethod void myUnitTest() 
    {
        
        RecordType objRecordDeudor=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Cliente deudor' limit 1];
        Account objAccDedudor= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor.Numero_de_telefono_celular__c='11111';
        objAccDedudor.Validar_numero_de_celular__c='11111';
        objAccDedudor.Numero_de_documento__c='11223344';
        objAccDedudor.Validar_numero_de_documento__c='11223344';
        objAccDedudor.LastName='Apellido';
        insert objAccDedudor;
                
        RecordType objRecord=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Codeudores' limit 1];
        Account objAcc= new Account(RecordTypeId=objRecord.Id);
        objAcc.Numero_de_telefono_celular__c='8768';
        objAcc.Validar_numero_de_celular__c='8768';
        objAcc.Numero_de_documento__c='8768999';
        objAcc.Validar_numero_de_documento__c='8768999';
        objAcc.LastName='dgdfg';
        objAcc.Cliente_deudor__c = objAccDedudor.Id;
        insert objAcc;
        
        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
        objRadicacion_de_credito.Codeudor_1__c = objAcc.Id;
        insert objRadicacion_de_credito;
        Informacion_comite__c infoActual = new Informacion_comite__c();
        infoActual.Radicacion__c=objRadicacion_de_credito.Id;
        Actualizacion_masiva_de_registros__c OBJActualizacion_masiva_de_registros= new Actualizacion_masiva_de_registros__c();
        OBJActualizacion_masiva_de_registros.Objeto_destino__c='Informacion_comite__c';
        OBJActualizacion_masiva_de_registros.Name='fdgdf';
        OBJActualizacion_masiva_de_registros.Objeto_origen__c='Account';
        OBJActualizacion_masiva_de_registros.Campo_Id__c='Radicacion__c';
        OBJActualizacion_masiva_de_registros.Campo_origen__c='Id';
        
        insert OBJActualizacion_masiva_de_registros;
        insert infoActual;
        InformacionComite_cls  classInformacionComite= new InformacionComite_cls();
        classInformacionComite.actualizarCodeudores(infoActual);
        
    }

    static testMethod void myUnitTest1() 
    {
        RecordType objRecordDeudor=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Cliente deudor' limit 1];
        Account objAccDedudor= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor.Numero_de_telefono_celular__c='11111';
        objAccDedudor.Validar_numero_de_celular__c='11111';
        objAccDedudor.Numero_de_documento__c='11223344';
        objAccDedudor.Validar_numero_de_documento__c='11223344';
        objAccDedudor.LastName='Apellido';
        insert objAccDedudor;

        RecordType objRecord=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Codeudores' limit 1];
        Account objAcc= new Account(RecordTypeId=objRecord.Id);
        objAcc.Numero_de_telefono_celular__c='8768';
        objAcc.Validar_numero_de_celular__c='8768';
        objAcc.Numero_de_documento__c='8768999';
        objAcc.Validar_numero_de_documento__c='8768999';
        objAcc.LastName='dgdfg';
        objAcc.Cliente_deudor__c = objAccDedudor.Id;
        insert objAcc;
        
        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
        objRadicacion_de_credito.Codeudor_2__c = objAcc.Id;
        insert objRadicacion_de_credito;
        Informacion_comite__c infoActual = new Informacion_comite__c();
        infoActual.Radicacion__c=objRadicacion_de_credito.Id;
        Actualizacion_masiva_de_registros__c OBJActualizacion_masiva_de_registros= new Actualizacion_masiva_de_registros__c();
        OBJActualizacion_masiva_de_registros.Objeto_destino__c='Informacion_comite__c';
        OBJActualizacion_masiva_de_registros.Name='fdgdf';
        OBJActualizacion_masiva_de_registros.Objeto_origen__c='Account';
        OBJActualizacion_masiva_de_registros.Campo_Id__c='Radicacion__c';
        OBJActualizacion_masiva_de_registros.Campo_origen__c='Id';
        
        insert OBJActualizacion_masiva_de_registros;
        insert infoActual;
        InformacionComite_cls  classInformacionComite= new InformacionComite_cls();
        classInformacionComite.actualizarCodeudores(infoActual);
        
    }

    static testMethod void myUnitTest2() 
    {
        RecordType objRecordDeudor=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Cliente deudor' limit 1];
        Account objAccDedudor= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor.Numero_de_telefono_celular__c='11111';
        objAccDedudor.Validar_numero_de_celular__c='11111';
        objAccDedudor.Numero_de_documento__c='11223344';
        objAccDedudor.Validar_numero_de_documento__c='11223344';
        objAccDedudor.LastName='Apellido';
        insert objAccDedudor;

        RecordType objRecord=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Codeudores' limit 1];
        Account objAcc= new Account(RecordTypeId=objRecord.Id);
        objAcc.Numero_de_telefono_celular__c='8768';
        objAcc.Validar_numero_de_celular__c='8768';
        objAcc.Numero_de_documento__c='8768999';
        objAcc.Validar_numero_de_documento__c='8768999';
        objAcc.LastName='dgdfg';
        objAcc.Cliente_deudor__c = objAccDedudor.Id;
        insert objAcc;

        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
        objRadicacion_de_credito.Codeudor_3__c = objAcc.Id;
        insert objRadicacion_de_credito;
        Informacion_comite__c infoActual = new Informacion_comite__c();
        infoActual.Radicacion__c=objRadicacion_de_credito.Id;
        Actualizacion_masiva_de_registros__c OBJActualizacion_masiva_de_registros= new Actualizacion_masiva_de_registros__c();
        OBJActualizacion_masiva_de_registros.Objeto_destino__c='Informacion_comite__c';
        OBJActualizacion_masiva_de_registros.Name='fdgdf';
        OBJActualizacion_masiva_de_registros.Objeto_origen__c='Account';
        OBJActualizacion_masiva_de_registros.Campo_Id__c='Radicacion__c';
        OBJActualizacion_masiva_de_registros.Campo_origen__c='Id';
        
        insert OBJActualizacion_masiva_de_registros;
        insert infoActual;
        InformacionComite_cls  classInformacionComite= new InformacionComite_cls();
        classInformacionComite.actualizarCodeudores(infoActual);
        
    }
    
}