src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Codeudores</relationshipLabel>
        <relationshipName>Codeudores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direccion_oficina__c</fullName>
        <label>Dirección oficina</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estado_de_la_solicitud__c</fullName>
        <label>Estado de la solicitud</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nueva Solicitud</fullName>
                </value>
                <value>
                    <fullName>Devuelta</fullName>
                </value>
                <value>
                    <fullName>Radicado</fullName>
                </value>
                <value>
                    <fullName>Referenciación</fullName>
                </value>
                <value>
                    <fullName>Digitalización</fullName>
                </value>
                <value>
                    <fullName>Análisis de crédito</fullName>
                </value>
                <value>
                    <fullName>Desistido</fullName>
                </value>
                <value>
                    <fullName>Comité de crédito</fullName>
                </value>
                <value>
                    <fullName>Archivo riesgos</fullName>
                </value>
                <value>
                    <fullName>Archivo operaciones</fullName>
                </value>
                <value>
                    <fullName>Legalizado</fullName>
                </value>
                <value>
                    <fullName>Devuelta a legalización</fullName>
                </value>
                <value>
                    <fullName>Desembolsado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <externalId>true</externalId>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Numero_de_telefono_celular__c</fullName>
        <label>Número de celular</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validar_numero_de_celular__c</fullName>
        <label>Validar número de celular</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validar_numero_de_documento__c</fullName>
        <label>Validar número de documento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo__c</fullName>
        <label>Id externo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo_destino__c</fullName>
        <label>Id externo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Meta__c.object
<CustomObject>
    <fields>
        <fullName>Meta__c</fullName>
        <label>Meta desem bogotá</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Metas</relationshipLabel>
        <relationshipName>Metas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Codeudor 1)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta</label>
        <referenceTo>Meta__c</referenceTo>
        <relationshipLabel>Meta</relationshipLabel>
        <relationshipName>Meta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resultado_del_Prevalidador__c</fullName>
        <label>Resultado del Prevalidador</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direccion_oficina_deudor__c</fullName>
        <label>Dirección oficina</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Telefono_oficina__c</fullName>
        <label>Teléfono oficina</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_familiar__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_personal__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estado_de_la_solicitud__c</fullName>
        <label>Estado de la solicitud</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nueva Solicitud</fullName>
                    <default>true</default>
                    <label>Nueva Solicitud</label>
                </value>
                <value>
                    <fullName>Reproceso</fullName>
                </value>
                <value>
                    <fullName>Radicada</fullName>
                </value>
                <value>
                    <fullName>Digitalizada</fullName>
                </value>
                <value>
                    <fullName>Documentos Revisados</fullName>
                </value>
                <value>
                    <fullName>Devuelta</fullName>
                </value>
                <value>
                    <fullName>Devuelta reproceso</fullName>
                </value>
                <value>
                    <fullName>Referenciada</fullName>
                </value>
                <value>
                    <fullName>Referenciación Devuelta</fullName>
                </value>
                <value>
                    <fullName>Analizada</fullName>
                </value>
                <value>
                    <fullName>Negada</fullName>
                </value>
                <value>
                    <fullName>Aplazada</fullName>
                </value>
                <value>
                    <fullName>Preaprobada</fullName>
                </value>
                <value>
                    <fullName>Desistida</fullName>
                </value>
                <value>
                    <fullName>Legalizada sin constructora y proyecto</fullName>
                </value>
                <value>
                    <fullName>Análisis de asignación de cupo</fullName>
                </value>
                <value>
                    <fullName>Legalizada</fullName>
                </value>
                <value>
                    <fullName>Legalización devuelta</fullName>
                </value>
                <value>
                    <fullName>Legalización verificada</fullName>
                </value>
                <value>
                    <fullName>Legalización archivada</fullName>
                </value>
                <value>
                    <fullName>Avalúo solicitado</fullName>
                </value>
                <value>
                    <fullName>Avalúo y carta definitiva solicitada</fullName>
                </value>
                <value>
                    <fullName>Avalúo favorable</fullName>
                </value>
                <value>
                    <fullName>Avalúo desfavorable</fullName>
                </value>
                <value>
                    <fullName>Documentos legales solicitados</fullName>
                </value>
                <value>
                    <fullName>Documentos legales recibidos</fullName>
                </value>
                <value>
                    <fullName>Documentos leglaes devueltos</fullName>
                </value>
                <value>
                    <fullName>Estudios de títulos favorable</fullName>
                </value>
                <value>
                    <fullName>Estudios de títulos desfavorable</fullName>
                </value>
                <value>
                    <fullName>Oferta vinculante generada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta</label>
        <referenceTo>Meta__c</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <label>Número de documento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/UpdateRegistersExtId_tst.cls
@isTest(SeeAllData=true)
private class UpdateRegistersExtId_tst 
{
    
    static testMethod void myUnitTest() 
    {
        UpdateRegistersExtId_cls classUpdateRegistersExtId= new UpdateRegistersExtId_cls();

        RecordType objRecordDeudor=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Cliente deudor' limit 1];
        Account objAccDedudor= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor.Numero_de_telefono_celular__c='11111';
        objAccDedudor.Validar_numero_de_celular__c='11111';
        objAccDedudor.Numero_de_documento__c='11223344';
        objAccDedudor.Validar_numero_de_documento__c='11223344';
        objAccDedudor.LastName='Apellido';
        insert objAccDedudor;

        RecordType objRecord=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Codeudores' limit 1];
        Account objAcc= new Account(RecordTypeId=objRecord.Id);
        objAcc.Numero_de_telefono_celular__c='8768';
        objAcc.Validar_numero_de_celular__c='8768';
        objAcc.Numero_de_documento__c='8768999';
        objAcc.Validar_numero_de_documento__c='8768999';
        objAcc.LastName='dgdfg';
        objAcc.Cliente_deudor__c = objAccDedudor.Id;
        insert objAcc;

        Actualizacionderegistros__c objObjeto_origen= new Actualizacionderegistros__c();
        objObjeto_origen.Name ='Prueba';
        objObjeto_origen.Id_externo_destino__c='Id';
        objObjeto_origen.Campo_destino__c = 'Direccion_oficina_deudor__c    ';
        objObjeto_origen.Campo_llave__c = 'Cliente_deudor__c';
        objObjeto_origen.Campo_origen__c = 'Direccion_oficina_deudor__c';
        objObjeto_origen.Id_externo__c = objAcc.Id;
        objObjeto_origen.Objeto_origen__c = 'Radicacion_de_credito__c';
        objObjeto_origen.Objeto_destino__c='Account';
        upsert objObjeto_origen;
        
        Opportunity opp = new Opportunity();
        opp.Resultado_del_Prevalidador__c = 'VIABLE';
        opp.Name = 'prueba';
        opp.StageName = 'Abierta';
        opp.CloseDate = Date.newInstance(2050,1,1);
        insert opp;
        
        Meta__c meta = new Meta__c();
        insert meta;        
        
        Solicitud_de_credito__c objSolicitud_de_credito= new Solicitud_de_credito__c();
        objSolicitud_de_credito.Codeudor_1__c=objAcc.Id;
        objSolicitud_de_credito.Estado_de_la_solicitud__c = 'Radicado';
        objSolicitud_de_credito.Oportunidad__c = opp.Id;
        objSolicitud_de_credito.Meta__c = meta.Id;
        insert objSolicitud_de_credito;
        
        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Direccion_oficina_deudor__c ='Prueba';
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
         objRadicacion_de_credito.Solicitud_de_credito__c=objSolicitud_de_credito.Id;
        insert objRadicacion_de_credito;
        
        sObject objRadicaciondecredito=objRadicacion_de_credito;
        classUpdateRegistersExtId.setRegister(objRadicaciondecredito,objObjeto_origen.Objeto_origen__c);
        classUpdateRegistersExtId.getSdfcId(objAcc.Id,objObjeto_origen);                                                                
    }

    static testMethod void myUnitTesttwo() 
    {
        UpdateRegistersExtId_cls classUpdateRegistersExtId= new UpdateRegistersExtId_cls();

        RecordType objRecordDeudor=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Cliente deudor' limit 1];
        Account objAccDedudor= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor.Numero_de_telefono_celular__c='11111';
        objAccDedudor.Validar_numero_de_celular__c='11111';
        objAccDedudor.Numero_de_documento__c='11223344';
        objAccDedudor.Validar_numero_de_documento__c='11223344';
        objAccDedudor.LastName='Apellido';
        insert objAccDedudor;

        RecordType objRecord=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Codeudores' limit 1];
        Account objAcc= new Account(RecordTypeId=objRecord.Id);
        objAcc.Numero_de_telefono_celular__c='8768';
        objAcc.Validar_numero_de_celular__c='8768';
        objAcc.Numero_de_documento__c='8768999';
        objAcc.Validar_numero_de_documento__c='8768999';
        objAcc.LastName='dgdfg';
        objAcc.Cliente_deudor__c = objAccDedudor.Id;
        insert objAcc;

        Actualizacionderegistros__c objObjeto_origen= new Actualizacionderegistros__c();
        objObjeto_origen.Name ='test';
        objObjeto_origen.Id_externo_destino__c='Id';
        objObjeto_origen.Campo_destino__c = 'Direccion_oficina__c';
        objObjeto_origen.Campo_llave__c = 'Cliente_deudor__c';
        objObjeto_origen.Campo_origen__c = 'Direccion_oficina_deudor__c';
        objObjeto_origen.Id_externo__c = objAcc.Id;
        objObjeto_origen.Objeto_origen__c = 'Radicacion_de_credito__c';
        objObjeto_origen.Objeto_destino__c='Account';
        upsert objObjeto_origen;
        
        Opportunity opp = new Opportunity();
        opp.Resultado_del_Prevalidador__c = 'VIABLE';
        opp.Name = 'prueba';
        opp.StageName = 'Abierta';
        opp.CloseDate = Date.newInstance(2050,1,1);
        insert opp;
        
        Meta__c meta = new Meta__c();
        insert meta;        
        
        Solicitud_de_credito__c objSolicitud_de_credito= new Solicitud_de_credito__c();
        objSolicitud_de_credito.Codeudor_1__c=objAcc.Id;
        objSolicitud_de_credito.Estado_de_la_solicitud__c = 'Radicado';
        objSolicitud_de_credito.Oportunidad__c = opp.Id;
        objSolicitud_de_credito.Meta__c = meta.Id;
        insert objSolicitud_de_credito;
        
        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Direccion_oficina_deudor__c ='Prueba';
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
        objRadicacion_de_credito.Solicitud_de_credito__c=objSolicitud_de_credito.Id;
        
        insert objRadicacion_de_credito;
        
        sObject objRadicaciondecredito=objRadicacion_de_credito;
        classUpdateRegistersExtId.setRegister(objRadicaciondecredito,objObjeto_origen.Objeto_origen__c);                                                              
    }
    
}