src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Canal_digital__c</fullName>
        <label>Canal digital</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Codeudores</relationshipLabel>
        <relationshipName>Codeudores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <externalId>true</externalId>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Cuenta</fullName>
        <active>true</active>
        <label>Cuenta</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Codeudor__c.object
<CustomObject>
    <description>Estará inicialmente relacionado con el Candidato y en el reposará la información correspondiente a los Codeudores.</description>
    <fields>
        <fullName>Candidato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidato</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Solicitantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <label>Número de documento</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Codeudor</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codeudores</pluralLabel>
    <recordTypes>
        <fullName>Codeudor</fullName>
        <active>true</active>
        <label>Codeudor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Canal_digital__c</fullName>
        <label>Canal digital</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Numero_de_identificacion__c</fullName>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Codeudor 1)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Codeudor 2)</relationshipLabel>
        <relationshipName>Oportunidades2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Codeudor 3)</relationshipLabel>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Canal_digital__c</fullName>
        <label>Canal digital</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <label>Número de documento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/LeadConversionTest.cls
@isTest
private class LeadConversionTest {

	@isTest static void conversion_de_lead_sin_codeudor() {
		Lead lead = TestDataFactory.createLead();
		System.assert(lead.Id != null, 'El candidato no fué insertado.');
		Test.startTest();
		
		Database.LeadConvertResult lcr = TestDataFactory.leadConversion(lead.Id);
		
		if(lcr.getErrors().size() > 0){
			System.debug('Errores al convertir el candidato: ');
			for(Database.Error error : lcr.getErrors()){
                System.debug(error.getStatusCode() + ': ' + error.getMessage());
                System.debug('Verificar los siguientes campos: ' + error.getFields());
            }
		} else {
			System.debug('Registros creados en la conversión');
			System.debug('Account: ' + lcr.getAccountId());
			System.debug('Contact: ' + lcr.getContactId());
			System.debug('Opportunity: ' + lcr.getOpportunityId());
		}

		System.assert(lcr.isSuccess()); 
		
		//Se creó la cuenta?
		Account acc = [select Id from Account where Numero_de_documento__c = :lead.Numero_de_identificacion__c];

		System.assert(
			[select count() from Account where Numero_de_documento__c = :lead.Numero_de_identificacion__c] == 1, 
			'Debe existir una cuenta con el número de indentificación del lead'
		);

		//Verificar que exista la solicitud de crédito con su información respectiva
		System.assert(
			[select count() from Solicitud_de_credito__c where Cliente_deudor__c = :acc.Id] == 1, 
			'Debe existir una Solicitud de credito'
		);

		//Verificar que exista la radicación de crédito con su información respectiva
		System.assert(
			[select count() from Radicacion_de_credito__c where Cliente_deudor__c = :acc.Id] == 1, 
			'Debe existir una radicación de crédito'
		);
		Test.stopTest();
		 
	}
	
	@isTest static void conversion_de_lead_con_un_codeudor() {
		Lead lead = TestDataFactory.createLead();
		Id codeudorId = TestDataFactory.createCodeudor(lead.Id);
		Test.startTest();
			
			Database.LeadConvertResult lcr = TestDataFactory.leadConversion(lead.Id);
			
			if(lcr.getErrors().size() > 0){
				System.debug('Errores al convertir el candidato: ');
				for(Database.Error error : lcr.getErrors()){
	                System.debug(error.getStatusCode() + ': ' + error.getMessage());
	                System.debug('Verificar los siguientes campos: ' + error.getFields());
	            }
			} 
				
			//Existe un deudor principal?
			Account deudorPrincipal = [select Id, Canal_digital__c, Numero_de_documento__c from Account where Numero_de_documento__c = :lead.Numero_de_identificacion__c];
			System.debug('conversion_de_lead_con_un_codeudor -> deudorPrincipal: ' + deudorPrincipal.Id);
			System.assertEquals(deudorPrincipal.Canal_digital__c, 'Si', 'La cuenta no se está creando con el identificador de canal digital');

			System.assert(
				[select count() from Account where Numero_de_documento__c = :lead.Numero_de_identificacion__c] == 1, 
				'Debe existir una cuenta con el número de indentificación del lead'
			);

			//El codeudor está enlazado a la cuenta principal?
			Codeudor__c cod = [select Numero_de_documento__c from Codeudor__c where Id = :codeudorId];
			Account codeudor = [select Id, Cliente_deudor__c, Numero_de_documento__c from Account where Numero_de_documento__c = :String.valueOf(cod.Numero_de_documento__c)];
			System.assertEquals(
				 deudorPrincipal.Id, codeudor.Cliente_deudor__c,
				'El codeudor no está enlazado al cliente plrincipal'
			);

			//Se creo la oportunidad?
			 Opportunity op = [select Id, AccountId, Codeudor_1__c from Opportunity where AccountId = :lcr.getAccountId()];
			 System.debug('conversion_de_lead_con_un_codeudor -> oportunidad creada');
			 System.debug(op);
			 System.assertEquals(op.Id, lcr.getOpportunityId(), 'No se creó la oportunidad en la conversión del candidato.');
			 System.assertEquals(op.AccountId, lcr.getAccountId(), 'La oportunidad no está enlazada a la cuenta principal');

			// Se actualizo correctamente el codeudor en la oportunidad?
			Account cuentaTipoCodeudor = [select Id from Account where Numero_de_documento__c = :String.valueOf(codeudor.Numero_de_documento__c)];
			System.debug('conversion_de_lead_con_un_codeudor -> cuentaTipoCodeudor: ' + cuentaTipoCodeudor.Id);
			System.assertEquals(op.Codeudor_1__c, cuentaTipoCodeudor.Id, 'El codeudor 1 no fué actualizado correctamente en la oportunidad');

			//Se creo la radicación de crédito?
			Radicacion_de_credito__c rc = [select Id, Codeudor_1__c, Cliente_deudor__c from Radicacion_de_credito__c where Cliente_deudor__c = :lcr.getAccountId()];
			System.assertEquals(rc.Codeudor_1__c, codeudor.Id, 'La radicación no esta enlazada al codeudor');


		Test.stopTest();
	}

	@isTest static void conversion_de_lead_con_dos_codeudores() {
		Lead lead = TestDataFactory.createLead();
		Id codeudor1 = TestDataFactory.createCodeudor(lead.Id);
		Id codeudor2 = TestDataFactory.createCodeudor(lead.Id);

		Test.startTest();
		 
			Database.LeadConvertResult lcr = TestDataFactory.leadConversion(lead.Id);

			if(lcr.getErrors().size() > 0){
				System.debug('Errores al convertir el candidato: ');
				for(Database.Error error : lcr.getErrors()){
	                System.debug(error.getStatusCode() + ': ' + error.getMessage());
	                System.debug('Verificar los siguientes campos: ' + error.getFields());
	            }
			} 

			System.assert(lcr.isSuccess(), 'La conversión no fué exitosa.');

			//Existen 2 cuentas de tipo codeudor enlazadas a la cuenta principal?
			System.assert(
				[select count() from Account where Cliente_deudor__c = :lcr.getAccountId()] == 2,
				'Se esperaba encontrar 2 cuentas de tipo codeudor'
			);

			//Se creo la oportunidad?
			Opportunity op = [select Id, AccountId, Codeudor_1__c, Codeudor_2__c from Opportunity where AccountId = :lcr.getAccountId()];
			//System.debug('conversion_de_lead_con_dos_codeudores -> oportunidad creada');
			//System.debug(op);
			System.assertEquals(op.Id, lcr.getOpportunityId(), 'No se creó la oportunidad en la conversión del candidato.');
			System.assertEquals(op.AccountId, lcr.getAccountId(), 'La oportunidad no está enlazada a la cuenta principal');


			// Se actualizaron correctamente los codeudores en la oportunidad?
			List<Account> lstCodeudores = [select Id from Account where Cliente_deudor__c = :lcr.getAccountId()]; 
			Map<Id, Account> mapCodeudores = new Map<Id, Account>(lstCodeudores);
			System.assert(mapCodeudores.containsKey(op.Codeudor_1__c), 'El codeudor 1 no fué actualizado correctamente en la oportunidad');
			System.assert(mapCodeudores.containsKey(op.Codeudor_2__c), 'El codeudor 2 no fué actualizado correctamente en la oportunidad');
		 
		Test.stopTest();
	}

	@isTest static void conversion_de_lead_con_tres_codeudores() {
		Lead lead = TestDataFactory.createLead();

		Id codeudor1 = TestDataFactory.createCodeudor(lead.Id);
		Id codeudor2 = TestDataFactory.createCodeudor(lead.Id);
		Id codeudor3 = TestDataFactory.createCodeudor(lead.Id);

		Test.startTest();
			Database.LeadConvertResult lcr = TestDataFactory.leadConversion(lead.Id);
			
			if(lcr.getErrors().size() > 0){
				System.debug('Errores al convertir el candidato: ');
				for(Database.Error error : lcr.getErrors()){
	                System.debug(error.getStatusCode() + ': ' + error.getMessage());
	                System.debug('Verificar los siguientes campos: ' + error.getFields());
	            }
			} 

			System.assert(lcr.isSuccess(), 'La conversión no fué exitosa.');

			//Existen 2 cuentas de tipo codeudor?
			System.assert(
				[select count() from Account where Cliente_deudor__c = :lcr.getAccountId()] == 3,
				'Se esperaba encontrar 3 cuentas de tipo codeudor'
			);

			//Se creo la oportunidad?
			Opportunity op = [select Id, AccountId, Codeudor_1__c, Codeudor_2__c, Codeudor_3__c from Opportunity where AccountId = :lcr.getAccountId()];
			//System.debug('conversion_de_lead_con_dos_codeudores -> oportunidad creada');
			//System.debug(op);
			System.assertEquals(op.Id, lcr.getOpportunityId(), 'No se creó la oportunidad en la conversión del candidato.');
			System.assertEquals(op.AccountId, lcr.getAccountId(), 'La oportunidad no está enlazada a la cuenta principal');


			// Se actualizaron correctamente los codeudores en la oportunidad?
			List<Account> lstCodeudores = [select Id from Account where Cliente_deudor__c = :lcr.getAccountId()]; 
			Map<Id, Account> mapCodeudores = new Map<Id, Account>(lstCodeudores);
			System.assert(mapCodeudores.containsKey(op.Codeudor_1__c), 'El codeudor 1 no fué actualizado correctamente en la oportunidad');
			System.assert(mapCodeudores.containsKey(op.Codeudor_2__c), 'El codeudor 2 no fué actualizado correctamente en la oportunidad');
			System.assert(mapCodeudores.containsKey(op.Codeudor_3__c), 'El codeudor 2 no fué actualizado correctamente en la oportunidad');
		
		Test.stopTest();
	}

	@isTest static void conversion_de_lead_con_cuatro_codeudores() {
		Lead lead = TestDataFactory.createLead();
		TestDataFactory.createCodeudor(lead.Id);
		TestDataFactory.createCodeudor(lead.Id);
		TestDataFactory.createCodeudor(lead.Id);
		Test.startTest();
			try {
				TestDataFactory.createCodeudor(lead.Id);
			} catch(Exception e){
				System.debug(e.getMessage());
			}

			System.assert(
				[select count() from Codeudor__c where Candidato__c = :lead.id] == 3,
				'Se esperaba encontrar 3 codeudores'
			);
		Test.stopTest();
		
	}
	
}