src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Codeudores</relationshipLabel>
        <relationshipName>Codeudores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numero_de_documento__c</fullName>
        <externalId>true</externalId>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Numero_de_telefono_celular__c</fullName>
        <label>Número de celular</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validar_numero_de_celular__c</fullName>
        <label>Validar número de celular</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validar_numero_de_documento__c</fullName>
        <label>Validar número de documento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Telefono_oficina__c</fullName>
        <label>Teléfono oficina</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_familiar__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_personal__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Referenciacion_y_verificacion__c.object
<CustomObject>
    <description>Identifica la información de los solicitantes para realizar el proceso de referenciación y verificación</description>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones (Codeudor 1)</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones (Codeudor 2)</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones (Codeudor 3)</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referenciación y verificación</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Consecutivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenciaciones y verificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReferenciacionVerificacion_tst.cls
@isTest (SeeAllData=true)
private class ReferenciacionVerificacion_tst {

    
      static testMethod void myUnitTest() 
    {
        RecordType objRecordDeudor=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Cliente deudor' limit 1];
        Account objAccDedudor= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor.Numero_de_telefono_celular__c='11111';
        objAccDedudor.Validar_numero_de_celular__c='11111';
        objAccDedudor.Numero_de_documento__c='11223344';
        objAccDedudor.Validar_numero_de_documento__c='11223344';
        objAccDedudor.LastName='Apellido';
        insert objAccDedudor;

      RecordType objRecord=[SELECT Id,Name,SobjectType FROM RecordType where Name ='Codeudores' limit 1];
      Account objAcc= new Account(RecordTypeId=objRecord.Id);
        objAcc.Numero_de_telefono_celular__c='8745454568';
        objAcc.Validar_numero_de_celular__c='8745454568';
        objAcc.Numero_de_documento__c='87687777';
        objAcc.Validar_numero_de_documento__c='87687777';
        objAcc.LastName='dgdfg';
        objAcc.Cliente_deudor__c = objAccDedudor.Id;
        insert objAcc;

        Account objAccDedudor2= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor2.Numero_de_telefono_celular__c='11111';
        objAccDedudor2.Validar_numero_de_celular__c='11111';
        objAccDedudor2.Numero_de_documento__c='11223355';
        objAccDedudor2.Validar_numero_de_documento__c='11223355';
        objAccDedudor2.LastName='Apellido';
        insert objAccDedudor2;

        Account objAcc2= new Account(RecordTypeId=objRecord.Id);
        objAcc2.Numero_de_telefono_celular__c='1454544234';
        objAcc2.Validar_numero_de_celular__c='1454544234';
        objAcc2.Numero_de_documento__c='145745';
        objAcc2.Validar_numero_de_documento__c='145745';
        objAcc2.LastName='pruebas';
        objAcc2.Cliente_deudor__c = objAccDedudor2.Id;
        insert objAcc2;

        Account objAccDedudor3= new Account(RecordTypeId=objRecordDeudor.Id);
        objAccDedudor3.Numero_de_telefono_celular__c='11111';
        objAccDedudor3.Validar_numero_de_celular__c='11111';
        objAccDedudor3.Numero_de_documento__c='11223366';
        objAccDedudor3.Validar_numero_de_documento__c='11223366';
        objAccDedudor3.LastName='Apellido';
        insert objAccDedudor3;

        Account objAcc3= new Account(RecordTypeId=objRecord.Id);
        objAcc3.Numero_de_telefono_celular__c='1296859835';
        objAcc3.Validar_numero_de_celular__c='1296859835';
        objAcc3.Numero_de_documento__c='12358998';
        objAcc3.Validar_numero_de_documento__c='12358998';
        objAcc3.LastName='pruebas3';
        objAcc3.Cliente_deudor__c = objAccDedudor3.Id;
        insert objAcc3;

         Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
       objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
       objRadicacion_de_credito.Telefono_oficina__c='46554';
       objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
       objRadicacion_de_credito.Codeudor_1__c = objAcc.Id;
       objRadicacion_de_credito.Codeudor_2__c=objAcc2.Id;
       objRadicacion_de_credito.Codeudor_3__c=objAcc3.Id;
       insert objRadicacion_de_credito;

       Referenciacion_y_verificacion__c referenciacionActual = new Referenciacion_y_verificacion__c();
       referenciacionActual.Radicacion_de_credito__c=objRadicacion_de_credito.Id;
     
       insert referenciacionActual;

        ReferenciacionVerificacion_cls classReferenciacionVerificacion= new ReferenciacionVerificacion_cls();
        classReferenciacionVerificacion.actualizarCodeudores(referenciacionActual);

       //ReferenciacionVerificacion_cls classReferenciacionVerificacion= new ReferenciacionVerificacion_cls();
       //classReferenciacionVerificacion.actualizarCodeudores(referenciacionActual);
    }
    


}