src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo__c</fullName>
        <label>Id externo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo_destino__c</fullName>
        <label>Id externo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/UpdateRegistersLookUp_tst.cls
@isTest (SeeAllData=true)
private class UpdateRegistersLookUp_tst 
{

    static testMethod void myUnitTest() 
    {
        UpdateRegistersLookUp_cls classUpdateRegistersLookUp= new UpdateRegistersLookUp_cls();
         List<Actualizacionderegistros__c> lstActualizacionderegistros=[SELECT Campo_destino__c,Campo_llave__c,Campo_origen__c,CreatedById,CreatedDate,Id,Id_externo__c,
                                                                              IsDeleted,LastModifiedById,LastModifiedDate,Name,Objeto_destino__c,Objeto_origen__c,
                                                                              SetupOwnerId,SystemModstamp FROM Actualizacionderegistros__c 
                                                                              where Id_externo_destino__c = null];
        Case objCase= new Case();
        sObject sobjOrigen=objCase;
        classUpdateRegistersLookUp.setRegister(sobjOrigen,lstActualizacionderegistros[0].Objeto_origen__c);
    }
}