src/objects/Actualizacion_masiva_de_registros__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Actualizará los objetos Información financiera, información comité y Referenciación y verificación desde la Radicación y se actualizará el objeto paz y salvo desde la solicitud de crédito</description>
    <fields>
        <fullName>Campo_Id__c</fullName>
        <label>Campo Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Actualización masiva de registros</label>
</CustomObject>

src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Informacion_financiera__c.object
<CustomObject>
    <fields>
        <fullName>Fecha_analisis__c</fullName>
        <label>Fecha análisis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipName>Informaciones_financieras</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/LogErrores__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>parametro1__c</fullName>
        <label>parametro1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LogErrores</label>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Fecha_analisis__c</fullName>
        <label>Fecha análisis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Telefono_oficina__c</fullName>
        <label>Teléfono oficina</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_familiar__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_personal__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/InfoFinancieraGestionarRadCredito_tst.cls
/**
* Avanxo Colombia
* @author           Raul Mora
* Proyect:          Credifamilia.
* Description:      Test class for InfoFinancieraGestionarRadCredito_Ctrl.
*
* Changes (Version)
* -------------------------------------
*           No.     Date            Author                          Description
*           -----   ----------      --------------------            ---------------
* @version   1.0    2015-11-25      Raul Mora (RM)                  Create class.
*************************************************************************************************************/
@isTest
private class InfoFinancieraGestionarRadCredito_tst 
{
    
    public Informacion_financiera__c createData()
    {
        Actualizacionderegistros__c objConfPer = new Actualizacionderegistros__c();
        objConfPer.Objeto_origen__c = 'Informacion_financiera__c';
        objConfPer.Objeto_destino__c = 'Radicacion_de_credito__c';
        objConfPer.Campo_origen__c = 'Fecha_analisis__c';
        objConfPer.Campo_destino__c = 'Fecha_analisis__c';
        objConfPer.Campo_llave__c = 'Radicacion_de_credito__c';
        objConfPer.Name = 'Test';
        insert objConfPer;
        
        LogErrores__c objLgErr = new LogErrores__c();
        objLgErr.Name = 'MasterControl';
        objLgErr.parametro1__c = 'Test';
        insert objLgErr;
        
        Actualizacion_masiva_de_registros__c objActMasReg = new Actualizacion_masiva_de_registros__c();
        objActMasReg.Name = 'Test';
        objActMasReg.Campo_origen__c = 'Fecha_analisis__c';
        objActMasReg.Campo_Id__c = 'Radicacion_de_credito__c';
        objActMasReg.Objeto_origen__c = 'Radicacion_de_credito__c';
        objActMasReg.Objeto_destino__c = 'Informacion_financiera__c';
        objActMasReg.Campo_destino__c = 'Fecha_analisis__c';
        insert objActMasReg;
        
        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
        insert objRadicacion_de_credito;
        
        Informacion_financiera__c objInfoFin = new Informacion_financiera__c();
        objInfoFin.Radicacion_de_credito__c = objRadicacion_de_credito.Id;
        insert objInfoFin;
        
        return objInfoFin;
    }
    
    static testMethod void myUnitTest() 
    {
        InfoFinancieraGestionarRadCredito_tst tstClass = new InfoFinancieraGestionarRadCredito_tst();
        Test.startTest();
            InfoFinancieraGestionarRadCredito_Ctrl ctrClass = new InfoFinancieraGestionarRadCredito_Ctrl( new ApexPages.StandardController( tstClass.createData() ) );
            ctrClass.StartProcess();
        Test.stopTest();
    }
    
}