src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo__c</fullName>
        <label>Id externo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
</CustomObject>

src/classes/RadicacionDeCredito_UpdateParent_tst.cls
@isTest (SeeAllData=true)
private class RadicacionDeCredito_UpdateParent_tst {

    static testMethod void myUnitTest() 
    {
    	List<Actualizacionderegistros__c> lstActualizacionderegistros=[SELECT Campo_destino__c,Campo_llave__c,Campo_origen__c,CreatedById,CreatedDate,Id,Id_externo__c,
                                                                              IsDeleted,LastModifiedById,LastModifiedDate,Name,Objeto_destino__c,Objeto_origen__c,
                                                                              SetupOwnerId,SystemModstamp FROM Actualizacionderegistros__c 
                                                                              where  Objeto_origen__c='Radicacion_de_credito__c'];
        RadicacionDeCredito_UpdateParent_cls classRadicacionDeCredito_UpdateParent= new RadicacionDeCredito_UpdateParent_cls();
        Radicacion_de_credito__c objRadicaciondecredito= new Radicacion_de_credito__c();
        classRadicacionDeCredito_UpdateParent.setRegister(objRadicaciondecredito);
        sObject objsObject=Schema.getGlobalDescribe().get(lstActualizacionderegistros[0].Objeto_destino__c).newSObject();
        classRadicacionDeCredito_UpdateParent.createObject(objsObject,objRadicaciondecredito,lstActualizacionderegistros[0]);
        
    }
}