src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo__c</fullName>
        <label>Id externo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Informacion_financiera__c.object
<CustomObject>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipName>Informaciones_financieras</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
</CustomObject>

src/classes/InfoFinancieraGestionarRadCredito_Ctrl.cls
public class InfoFinancieraGestionarRadCredito_Ctrl 
{
    sObject sobjOrigenTmp;
    public InfoFinancieraGestionarRadCredito_Ctrl(ApexPages.StandardController controller)
    {
    	List<Actualizacionderegistros__c> lstActualizacionderegistros=[SELECT Campo_destino__c,Campo_llave__c,Campo_origen__c,Id,Id_externo__c,
                                                                              IsDeleted,Name,Objeto_destino__c,Objeto_origen__c,
                                                                              SetupOwnerId,SystemModstamp FROM Actualizacionderegistros__c 
                                                                              where  Objeto_origen__c = 'Informacion_financiera__c' and Objeto_destino__c = 'Radicacion_de_credito__c'];
        Informacion_financiera__c objInformacion_financiera= (Informacion_financiera__c)controller.getRecord();
        Informacion_financiera__c objInformacion_financiera1;
        String strQuery='SELECT Id, Radicacion_de_credito__c ';
                                                                       
		for(Actualizacionderegistros__c objActualizacionderegistros : lstActualizacionderegistros)
		{
			try
			{
				strQuery+=', ';
				strQuery+=objActualizacionderegistros.Campo_origen__c;
			}
			catch(exception e)
			{
				system.debug('\nError --> ' + e.getmessage());
			}
		}
		
		strQuery+=' FROM Informacion_financiera__c WHERE Id=\''+ objInformacion_financiera.Id +'\' LIMIT 1';
		
    	system.Debug('\n\n -->Query Select Objeto Origen --> ' + strQuery);
    	
    	List<sObject> lstObjetoOrigen = Database.query(strQuery);
    	
    	if( !lstObjetoOrigen.isEmpty() )
    	{
    		objInformacion_financiera1 = (Informacion_financiera__c) lstObjetoOrigen.get(0);
    	}
       
        sobjOrigenTmp=objInformacion_financiera1;
    }
    public void StartProcess()
    {
        CheckParentUpdate_cls classCheckParentUpdate= new CheckParentUpdate_cls(sobjOrigenTmp,'Informacion_financiera__c', 'Radicacion_de_credito__c');
        classCheckParentUpdate.CheckUpdate();
    }    
        
       
}