src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_externo__c</fullName>
        <label>Id externo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
</CustomObject>

src/objects/Referenciacion_y_verificacion__c.object
<CustomObject>
    <description>Identifica la información de los solicitantes para realizar el proceso de referenciación y verificación</description>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referenciación y verificación</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Consecutivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenciaciones y verificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RefinanReferenGestionarRadCredito_ctr.cls
/**
* Avanxo Colombia
* @author 			Raul Mora
* Proyect:			Credifamilia.
* Description:		Class to verify if the parent object Radicación de crédito is up to date, if not it proceed to update it.
*
* Changes (Version)
* -------------------------------------
*			No.		Date			Author							Description
*			-----	----------		--------------------			---------------
* @version	 1.0	2015-11-24		Raul Mora (RM)   				Create class.
*************************************************************************************************************/
public with sharing class RefinanReferenGestionarRadCredito_ctr 
{
	
	sObject sobjOrigenTmp;
    public RefinanReferenGestionarRadCredito_ctr(ApexPages.StandardController controller)
    {
    	List<Actualizacionderegistros__c> lstActualizacionderegistros=[SELECT Campo_destino__c,Campo_llave__c,Campo_origen__c,Id,Id_externo__c,
                                                                              IsDeleted,Name,Objeto_destino__c,Objeto_origen__c,
                                                                              SetupOwnerId,SystemModstamp FROM Actualizacionderegistros__c 
                                                                              where  Objeto_origen__c = 'Referenciacion_y_verificacion__c' and Objeto_destino__c = 'Radicacion_de_credito__c'];
        Referenciacion_y_verificacion__c objRefVer = (Referenciacion_y_verificacion__c)controller.getRecord();
        Referenciacion_y_verificacion__c objRefVer1;
        String strQuery='SELECT Id, Radicacion_de_credito__c ';
                                                                       
		for(Actualizacionderegistros__c objActualizacionderegistros : lstActualizacionderegistros)
		{
			try
			{
				strQuery+=', ';
				strQuery+=objActualizacionderegistros.Campo_origen__c;
			}
			catch(exception e)
			{
				system.debug('\nError --> ' + e.getmessage());
			}
		}
		
		strQuery+=' FROM Referenciacion_y_verificacion__c WHERE Id=\''+ objRefVer.Id +'\' LIMIT 1';
		
    	system.Debug('\n\n -->Query Select Objeto Origen --> ' + strQuery);
    	
    	List<sObject> lstObjetoOrigen = Database.query(strQuery);
    	
    	if( !lstObjetoOrigen.isEmpty() )
    	{
    		objRefVer1 = (Referenciacion_y_verificacion__c) lstObjetoOrigen.get(0);
    	}
       
        sobjOrigenTmp=objRefVer1;
    }
    public void StartProcess()
    {
        CheckParentUpdate_cls classCheckParentUpdate= new CheckParentUpdate_cls(sobjOrigenTmp,'Referenciacion_y_verificacion__c', 'Radicacion_de_credito__c');
        classCheckParentUpdate.CheckUpdate();
    }

}