src/objects/Actualizacion_masiva_de_registros__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Actualizará los objetos Información financiera, información comité y Referenciación y verificación desde la Radicación y se actualizará el objeto paz y salvo desde la solicitud de crédito</description>
    <fields>
        <fullName>Campo_Id__c</fullName>
        <label>Campo Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Actualización masiva de registros</label>
</CustomObject>

src/objects/Actualizacionderegistros__c.object
<CustomObject>
    <fields>
        <fullName>Campo_destino__c</fullName>
        <label>Campo destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_llave__c</fullName>
        <label>Campo llave</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campo_origen__c</fullName>
        <label>Campo origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_destino__c</fullName>
        <label>Objeto destino</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objeto_origen__c</fullName>
        <label>Objeto origen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/LogErrores__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>parametro1__c</fullName>
        <label>parametro1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LogErrores</label>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cargo_deudor__c</fullName>
        <label>Cargo deudor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_oficina__c</fullName>
        <label>Teléfono oficina</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_familiar__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_parentesco_personal__c</fullName>
        <label>Teléfono</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Referenciacion_y_verificacion__c.object
<CustomObject>
    <description>Identifica la información de los solicitantes para realizar el proceso de referenciación y verificación</description>
    <fields>
        <fullName>Cargo_deudor__c</fullName>
        <label>Cargo deudor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referenciación y verificación</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Consecutivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenciaciones y verificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RefinanReferenGestionarRadCredito_tst.cls
/**
* Avanxo Colombia
* @author           Raul Mora
* Proyect:          Credifamilia.
* Description:      Test class for RefinanReferenGestionarRadCredito_ctr.
*
* Changes (Version)
* -------------------------------------
*           No.     Date            Author                          Description
*           -----   ----------      --------------------            ---------------
* @version   1.0    2015-11-25      Raul Mora (RM)                  Create class.
*************************************************************************************************************/
@isTest
private class RefinanReferenGestionarRadCredito_tst 
{
    public Referenciacion_y_verificacion__c createData()
    {
        Actualizacionderegistros__c objConfPer = new Actualizacionderegistros__c();
        objConfPer.Objeto_origen__c = 'Referenciacion_y_verificacion__c';
        objConfPer.Objeto_destino__c = 'Radicacion_de_credito__c';
        objConfPer.Campo_origen__c = 'Cargo_deudor__c';
        objConfPer.Campo_destino__c = 'Cargo_deudor__c';
        objConfPer.Campo_llave__c = 'Radicacion_de_credito__c';
        objConfPer.Name = 'Test';
        insert objConfPer;
        
        LogErrores__c objLgErr = new LogErrores__c();
        objLgErr.Name = 'MasterControl';
        objLgErr.parametro1__c = 'Test';
        insert objLgErr;
        
        Actualizacion_masiva_de_registros__c objActMasReg = new Actualizacion_masiva_de_registros__c();
        objActMasReg.Name = 'Test';
        objActMasReg.Campo_origen__c = 'Cargo_deudor__c';
        objActMasReg.Campo_Id__c = 'Radicacion_de_credito__c';
        objActMasReg.Objeto_origen__c = 'Radicacion_de_credito__c';
        objActMasReg.Objeto_destino__c = 'Referenciacion_y_verificacion__c';
        objActMasReg.Campo_destino__c = 'Cargo_deudor__c';
        insert objActMasReg;
        
        Radicacion_de_credito__c objRadicacion_de_credito= new Radicacion_de_credito__c();
        objRadicacion_de_credito.Telefono_parentesco_familiar__c='46554';
        objRadicacion_de_credito.Telefono_oficina__c='46554';
        objRadicacion_de_credito.Telefono_parentesco_personal__c='46554';
        insert objRadicacion_de_credito;
        
        Referenciacion_y_verificacion__c objRefVer = new Referenciacion_y_verificacion__c();
        objRefVer.Radicacion_de_credito__c = objRadicacion_de_credito.Id;
        insert objRefVer;
        
        return objRefVer;
    }

    static testMethod void myUnitTest() 
    {
        RefinanReferenGestionarRadCredito_tst tstClass = new RefinanReferenGestionarRadCredito_tst();
        Test.startTest();
            RefinanReferenGestionarRadCredito_ctr ctrClass = new RefinanReferenGestionarRadCredito_ctr( new ApexPages.StandardController( tstClass.createData() ) );
            ctrClass.StartProcess();
        Test.stopTest();
    }
    
}