src/objects/Calificacion__c.object
<CustomObject>
    <customHelpPage>calificacion</customHelpPage>
    <description>Sistema de validación financiera del cliente para otorgar un crédito.</description>
    <fields>
        <fullName>Aportes_de_recursos_propios__c</fullName>
        <label>Aportes de recursos propios</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Calificacion__c</fullName>
        <description>Resultado de la calificación</description>
        <label>Calificación</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disponible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Verifica si este usuario ya fué calificado en los últimos 60 días</description>
        <label>Disponible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eximido_de_calificacion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eximido de calificación</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Informacion_comite__c</fullName>
        <label>Información comité</label>
        <referenceTo>Informacion_comite__c</referenceTo>
        <relationshipLabel>Calificaciones</relationshipLabel>
        <relationshipName>Calificaciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>N_mero_de_cr_ditos_vigentes__c</fullName>
        <label>Número de créditos vigentes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numero_de_Consultas__c</fullName>
        <description>Número de consultas con el sector financiero y cooperativo.</description>
        <inlineHelpText>Número de consultas con el sector financiero y cooperativo.</inlineHelpText>
        <label>Número de Consultas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Porcentaje_de_utilizacion_tc__c</fullName>
        <description>Saldo / Cupo</description>
        <label>% utilización tarjeta de credito</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relacion_cuota_ingreso__c</fullName>
        <label>Relación cuota ingreso</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Calificación</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Calificación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calificaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Informacion_comite__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Información comité</relationshipLabel>
        <relationshipName>Informacion_comite</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credito_solicitado__c</fullName>
        <label>Crédito solicitado</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ind_relacion_cuota_ingeso_neto_propuesta__c</fullName>
        <formula>Valor_cuota_sugerida__c / Ingreso_neto_total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ind. relación cuota/ingeso neto dispon.</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>N_de_creditos_vigentes__c</fullName>
        <label>N° de creditos vigentes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numero_de_consultas__c</fullName>
        <label>Número de consultas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Relacion_cuota_ingreso__c</fullName>
        <formula>Valor_cuota_solicitada__c /  Ingresos_mes__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relación cuota ingreso</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relacion_cuota_ingreso_propuesta__c</fullName>
        <formula>Valor_cuota_sugerida__c / Ingresos_mes__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relación cuota ingreso</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Subsidio__c</fullName>
        <label>Subsidio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valor_total_del_Inmueble__c</fullName>
        <formula>Credito_solicitado__c + Compromiso_de_pago__c + Ahorro_programado__c + Venta_inmueble__c + Otros_creditos__c + Credito_fondo_de_empleados__c + Cesantias__c + Subsidio__c+ Diferencia_Mejoramiento__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valor total del Inmueble</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Informacion_financiera__c.object
<CustomObject>
    <fields>
        <fullName>Calificacion__c</fullName>
        <label>Calificación</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Informaciones_financieras</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo2__c</fullName>
        <label>Saldo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Saldo__c</fullName>
        <label>Saldo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valor_cupo2__c</fullName>
        <label>Valor /cupo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valor_cupo__c</fullName>
        <label>Valor /cupo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valor_total_del_inmueble__c</fullName>
        <label>Valor total del inmueble</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/CalificacionCtrl.cls
public with sharing class CalificacionCtrl {
    
    Transient public Id idInfoComite {get; set;}
    Transient public Informacion_comite__c infoComite {get; set;}
    Transient public Calificacion__c calificacion {get; set;}
    Transient public List<Calificacion__c> lstCalificaciones { get; set; } 
    Transient public Double porcentajeDeUsoTc { get; set; }
    
    public CalificacionCtrl(ApexPages.StandardController stdController){
        System.debug(stdController.getRecord());
        idInfoComite = ApexPages.currentPage().getParameters().get('id');
        if(idInfoComite != null){
            this.calificacion = new Calificacion__c(Informacion_comite__c = idInfoComite, Disponible__c = true);
            checkAvailability();
            this.infoComite = getInfoComite();
            setPorcentajeDeUsoTc();
        }   
    }
    
    /**
     * Obtiene la información comité
     **/
    public Informacion_comite__c getInfoComite(){
         Informacion_comite__c ic = [
                select 
                    Relacion_cuota_ingreso_propuesta__c,
                    Ind_relacion_cuota_ingeso_neto_propuesta__c,
                    Numero_de_consultas__c,
                    Cliente_deudor__c,
             		N_de_creditos_vigentes__c,
             		Credito_solicitado__c,
             		Subsidio__c,
             		Valor_total_del_Inmueble__c
             		
                from 
                    Informacion_comite__c
                where Id = :this.idInfoComite
            ];
            
            return ic;
    }
    
    /**
     * Verifica si este usuario ya fué calificado en los últimos 60 días
     * 
     * */
    private void checkAvailability(){
        
        this.lstCalificaciones = [
            select   
                c.Id,
                c.Name,
                c.Porcentaje_de_utilizacion_tc__c,
                c.Aportes_de_recursos_propios__c,
                c.Calificacion__c,
                c.Eximido_de_calificacion__c,
                c.CreatedDate,
                c.Informacion_comite__c,
                c.Numero_de_Consultas__c,
                c.N_mero_de_cr_ditos_vigentes__c,
                c.Relacion_cuota_ingreso__c
               
            from 
            	Calificacion__c c 
            where 
            	c.CreatedDate = LAST_N_DAYS:60
            and
            	c.Informacion_comite__c = :idInfoComite
        ];
        
        if(lstCalificaciones.size() > 2){
            this.calificacion.Disponible__c = false;
            ApexPages.addmessage(
                new ApexPages.message(
                        ApexPages.severity.ERROR,
                        'El usuario ya fué calificado dos veces en los últimos 60 días'
                )
            );
        }        
    }
    
    
    /**
     * Calcula el porcentaje de utilización de la tarjeta de crédito
     */
    public void setPorcentajeDeUsoTc(){
        
         
        Informacion_financiera__c infoFinanciera = [
            Select 
                Valor_cupo__c, 
                Valor_cupo2__c, 
                Saldo__c, 
                Saldo2__c
            From 
                Informacion_financiera__c  
            where Cliente_deudor__c = :this.infoComite.Cliente_deudor__c 
                order by CreatedDate desc limit 1
        ];
        
        Double valorCupo = (infoFinanciera.Valor_cupo__c != null) ? infoFinanciera.Valor_cupo__c : 0;
        Double valorCupo2 = (infoFinanciera.Valor_cupo2__c != null) ? infoFinanciera.Valor_cupo2__c : 0;
        Double saldo = (infoFinanciera.Saldo__c != null) ? infoFinanciera.Saldo__c : 0;
        Double saldo2 = (infoFinanciera.Saldo2__c != null) ? infoFinanciera.Saldo2__c : 0;
        Double cupo = valorCupo + valorCupo2;
        Double saldoTotal = saldo + saldo2;
        this.porcentajeDeUsoTc = ( cupo != 0 ) ? saldoTotal/cupo : -0.09434;
        System.debug('El porcentaje de uso TC es: ' + this.porcentajeDeUsoTc);
           
    }
    
    /**
     * Calcula los aportes propios
     * */
    public Decimal aportesPropios(){
        Informacion_comite__c ic = getInfoComite();
        Decimal recursosPropios = (Decimal)(ic.Valor_total_del_Inmueble__c - ic.Credito_solicitado__c - ic.Subsidio__c)/ic.Valor_total_del_Inmueble__c;
        return (recursosPropios > 0.5) ? 0.5 : recursosPropios;
    }
    
    /**
     * Crea una calificación
     */
   
    public void Calificar(){
        Calificacion__c calificacion = new Calificacion__c(
            Aportes_de_recursos_propios__c		= this.aportesPropios(),
            N_mero_de_cr_ditos_vigentes__c      = this.infoComite.N_de_creditos_vigentes__c,
            Relacion_cuota_ingreso__c           = this.infoComite.Relacion_cuota_ingreso__c,
            Numero_de_Consultas__c              = this.infoComite.Numero_de_consultas__c,
            Porcentaje_de_utilizacion_tc__c     = this.porcentajeDeUsoTc,
            Calificacion__c                     = (Double) (
                ((this.infoComite.N_de_creditos_vigentes__c != null) ? this.infoComite.N_de_creditos_vigentes__c : 0) +
                ((this.infoComite.Relacion_cuota_ingreso__c != null) ? this.infoComite.Relacion_cuota_ingreso__c : 0) +
                ((this.infoComite.Numero_de_consultas__c  != null) ? this.infoComite.Numero_de_consultas__c : 0)
            ) / 100
        );
    
        try {
            insert calificacion;
        } catch (Exception ex){
            ApexPages.addMessages(ex);
        }
        
        //this.calificacion = calificacion;
        //this.lstCalificaciones.add(calificacion);
    }
    
}