src/objects/Controldeestados__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Control de estados en la solicitud de crédito por perfil</description>
    <fields>
        <fullName>Estado_1__c</fullName>
        <label>Estado 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estado_2__c</fullName>
        <label>Estado 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Perfil__c</fullName>
        <label>Perfil</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Control de estados en la solicitud</label>
</CustomObject>

src/objects/Meta__c.object
<CustomObject>
    <fields>
        <fullName>Meta__c</fullName>
        <label>Meta desem bogotá</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Metas</relationshipLabel>
        <relationshipName>Metas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Meta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta</label>
        <referenceTo>Meta__c</referenceTo>
        <relationshipLabel>Meta</relationshipLabel>
        <relationshipName>Meta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resultado_del_Prevalidador__c</fullName>
        <label>Resultado del Prevalidador</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Estado_de_la_solicitud__c</fullName>
        <label>Estado de la solicitud</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nueva Solicitud</fullName>
                    <default>true</default>
                    <label>Nueva Solicitud</label>
                </value>
                <value>
                    <fullName>Reproceso</fullName>
                </value>
                <value>
                    <fullName>Radicada</fullName>
                </value>
                <value>
                    <fullName>Digitalizada</fullName>
                </value>
                <value>
                    <fullName>Documentos Revisados</fullName>
                </value>
                <value>
                    <fullName>Devuelta</fullName>
                </value>
                <value>
                    <fullName>Devuelta reproceso</fullName>
                </value>
                <value>
                    <fullName>Referenciada</fullName>
                </value>
                <value>
                    <fullName>Referenciación Devuelta</fullName>
                </value>
                <value>
                    <fullName>Analizada</fullName>
                </value>
                <value>
                    <fullName>Negada</fullName>
                </value>
                <value>
                    <fullName>Aplazada</fullName>
                </value>
                <value>
                    <fullName>Preaprobada</fullName>
                </value>
                <value>
                    <fullName>Desistida</fullName>
                </value>
                <value>
                    <fullName>Legalizada sin constructora y proyecto</fullName>
                </value>
                <value>
                    <fullName>Análisis de asignación de cupo</fullName>
                </value>
                <value>
                    <fullName>Legalizada</fullName>
                </value>
                <value>
                    <fullName>Legalización devuelta</fullName>
                </value>
                <value>
                    <fullName>Legalización verificada</fullName>
                </value>
                <value>
                    <fullName>Legalización archivada</fullName>
                </value>
                <value>
                    <fullName>Avalúo solicitado</fullName>
                </value>
                <value>
                    <fullName>Avalúo y carta definitiva solicitada</fullName>
                </value>
                <value>
                    <fullName>Avalúo favorable</fullName>
                </value>
                <value>
                    <fullName>Avalúo desfavorable</fullName>
                </value>
                <value>
                    <fullName>Documentos legales solicitados</fullName>
                </value>
                <value>
                    <fullName>Documentos legales recibidos</fullName>
                </value>
                <value>
                    <fullName>Documentos leglaes devueltos</fullName>
                </value>
                <value>
                    <fullName>Estudios de títulos favorable</fullName>
                </value>
                <value>
                    <fullName>Estudios de títulos desfavorable</fullName>
                </value>
                <value>
                    <fullName>Oferta vinculante generada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta</label>
        <referenceTo>Meta__c</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/SolicitudCreditoVerifyProfile_tst.cls
@isTest
private class SolicitudCreditoVerifyProfile_tst {

    static testMethod void myUnitTest() 
    {
       SolicitudCreditoVerifyProfile classSolicitudCreditoVerifyProfile= new SolicitudCreditoVerifyProfile();

       Controldeestados__c controlador = new Controldeestados__c();
       controlador.Name ='nombre1';
       controlador.Estado_2__c ='Archivo riesgos';
       controlador.Estado_1__c ='Comité de crédito';
       controlador.Perfil__c ='Coordinadora de Riesgo y Crédito,Analista de Crédito,Administrador del sistema';
       insert controlador;

        Opportunity opp = new Opportunity();
        opp.Resultado_del_Prevalidador__c = 'VIABLE';
        opp.Name = 'prueba';
        opp.StageName = 'Abierta';
        opp.CloseDate = Date.newInstance(2050,1,1);
        insert opp;
        
        Meta__c meta = new Meta__c();
        insert meta;

       Solicitud_de_credito__c objOldSolicitudcredito = new Solicitud_de_credito__c();
       objOldSolicitudcredito.Estado_de_la_solicitud__c ='Comité de crédito';
        objOldSolicitudcredito.Oportunidad__c = opp.Id;
        objOldSolicitudcredito.Meta__c = meta.Id;
       insert objOldSolicitudcredito;

       Solicitud_de_credito__c objNewSolicitudcredito= new Solicitud_de_credito__c();
       objNewSolicitudcredito.Estado_de_la_solicitud__c='Archivo riesgos'; 
        objNewSolicitudcredito.Oportunidad__c = opp.Id;
        objNewSolicitudcredito.Meta__c = meta.Id;
       insert objNewSolicitudcredito;

       classSolicitudCreditoVerifyProfile.verifyProfile(objOldSolicitudcredito,objNewSolicitudcredito);
    }
}