src/objects/Controldeestados__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Control de estados en la solicitud de crédito por perfil</description>
    <fields>
        <fullName>Estado_1__c</fullName>
        <label>Estado 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estado_2__c</fullName>
        <label>Estado 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Perfil__c</fullName>
        <label>Perfil</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Control de estados en la solicitud</label>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Estado_de_la_solicitud__c</fullName>
        <label>Estado de la solicitud</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nueva Solicitud</fullName>
                    <default>true</default>
                    <label>Nueva Solicitud</label>
                </value>
                <value>
                    <fullName>Reproceso</fullName>
                </value>
                <value>
                    <fullName>Radicada</fullName>
                </value>
                <value>
                    <fullName>Digitalizada</fullName>
                </value>
                <value>
                    <fullName>Documentos Revisados</fullName>
                </value>
                <value>
                    <fullName>Devuelta</fullName>
                </value>
                <value>
                    <fullName>Devuelta reproceso</fullName>
                </value>
                <value>
                    <fullName>Referenciada</fullName>
                </value>
                <value>
                    <fullName>Referenciación Devuelta</fullName>
                </value>
                <value>
                    <fullName>Analizada</fullName>
                </value>
                <value>
                    <fullName>Negada</fullName>
                </value>
                <value>
                    <fullName>Aplazada</fullName>
                </value>
                <value>
                    <fullName>Preaprobada</fullName>
                </value>
                <value>
                    <fullName>Desistida</fullName>
                </value>
                <value>
                    <fullName>Legalizada sin constructora y proyecto</fullName>
                </value>
                <value>
                    <fullName>Análisis de asignación de cupo</fullName>
                </value>
                <value>
                    <fullName>Legalizada</fullName>
                </value>
                <value>
                    <fullName>Legalización devuelta</fullName>
                </value>
                <value>
                    <fullName>Legalización verificada</fullName>
                </value>
                <value>
                    <fullName>Legalización archivada</fullName>
                </value>
                <value>
                    <fullName>Avalúo solicitado</fullName>
                </value>
                <value>
                    <fullName>Avalúo y carta definitiva solicitada</fullName>
                </value>
                <value>
                    <fullName>Avalúo favorable</fullName>
                </value>
                <value>
                    <fullName>Avalúo desfavorable</fullName>
                </value>
                <value>
                    <fullName>Documentos legales solicitados</fullName>
                </value>
                <value>
                    <fullName>Documentos legales recibidos</fullName>
                </value>
                <value>
                    <fullName>Documentos leglaes devueltos</fullName>
                </value>
                <value>
                    <fullName>Estudios de títulos favorable</fullName>
                </value>
                <value>
                    <fullName>Estudios de títulos desfavorable</fullName>
                </value>
                <value>
                    <fullName>Oferta vinculante generada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/SolicitudCreditoVerifyProfile.cls
public class SolicitudCreditoVerifyProfile
{
    public SolicitudCreditoVerifyProfile()
    {
    	
    }
    
    public void verifyProfile(Solicitud_de_credito__c objOldSolicitudcredito,Solicitud_de_credito__c objNewSolicitudcredito)
    {
    	String strUserProfile= UserInfo.getProfileId();
    	Boolean blnIsValid=false;
    	List<Controldeestados__c> lstControlDeEstados=[SELECT Estado_1__c,Estado_2__c,Perfil__c 
    	                                       FROM Controldeestados__c where Estado_1__c=:objOldSolicitudcredito.Estado_de_la_solicitud__c 
    	                                           and Estado_2__c=:objNewSolicitudcredito.Estado_de_la_solicitud__c limit 1];
    	                                           
    	Profile objProfile=[SELECT Id,Name FROM Profile where Id=:UserInfo.getProfileId()];
    	
    	if(lstControlDeEstados.size()==1)
    	{
    		List<String> lstConfProfiles=lstControlDeEstados[0].Perfil__c.split(',');
    		
    		for(String strProfiles:lstConfProfiles)
    		{
    			if(strProfiles==objProfile.Name)
    			{
    				blnIsValid=true;
    			}
    		}
    	}
    	
    	System.debug('DebugLine31: '+blnIsValid);
    	
    	//if(objNewSolicitudcredito.Estado_de_la_solicitud__c != null && objOldSolicitudcredito.Estado_de_la_solicitud__c != null || (objNewSolicitudcredito.Estado_de_la_solicitud__c != null && objOldSolicitudcredito.Estado_de_la_solicitud__c != null && objNewSolicitudcredito.Estado_de_la_solicitud__c.equals(objOldSolicitudcredito.Estado_de_la_solicitud__c)))
    	{
    		System.debug('DebugLine33: '+blnIsValid);
    		
    	//	blnIsValid=true;
    	}
    	
    	   	
    	if(!blnIsValid)
    	{
    		objNewSolicitudcredito.addError('Perfil no autorizado!');
    	}
    }
}