src/objects/Informacion_financiera__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Informaciones_financieras</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Informaciones_financieras1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Informaciones_financieras2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Informaciones_financieras3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Radicacion__c</fullName>
        <externalId>true</externalId>
        <label>Id Radicación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipName>Informaciones_financieras</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Radicacion__c</fullName>
        <externalId>true</externalId>
        <label>Id Radicación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/InformacionFinanciera_cls.cls
public with sharing class InformacionFinanciera_cls {
	
	public void actualizarCodeudores(Informacion_financiera__c infoActual)
	{
		List<Radicacion_de_credito__c> lstInfoFinanciera = [SELECT Name, Cliente_deudor__c,Codeudor_1__c,Codeudor_2__c,Codeudor_3__c FROM Radicacion_de_credito__c WHERE Id =:infoActual.Radicacion_de_credito__c];
		if( !lstInfoFinanciera.isEmpty() )
		{
			infoActual.Cliente_deudor__c = lstInfoFinanciera.get(0).Cliente_deudor__c;
			if(lstInfoFinanciera.get(0).Codeudor_1__c != null)
			{
				infoActual.Codeudor_1__c = lstInfoFinanciera.get(0).Codeudor_1__c;
			}
			if(lstInfoFinanciera.get(0).Codeudor_2__c != null)
			{
				infoActual.Codeudor_2__c = lstInfoFinanciera.get(0).Codeudor_2__c;
			}
			if(lstInfoFinanciera.get(0).Codeudor_3__c != null)
			{
				infoActual.Codeudor_3__c = lstInfoFinanciera.get(0).Codeudor_3__c;
			}
			infoActual.Id_Radicacion__c = lstInfoFinanciera.get(0).Name;
		}
	}
}