src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Canal_digital__c</fullName>
        <label>Canal digital</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Concepto_del_candidato__c</fullName>
        <label>Resultado del Prevalidador</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No prevalidado</fullName>
                </value>
                <value>
                    <fullName>VIABLE</fullName>
                </value>
                <value>
                    <fullName>NO VIABLE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Numero_de_celular__c</fullName>
        <label>Número de celular</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_de_identificacion__c</fullName>
        <label>Número de documento</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Puntaje_data_credito__c</fullName>
        <label>Puntaje data crédito</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/ConteoLead.cls
@IsTest
public class ConteoLead{
    static testmethod void insertLead(){
        Lead l = new Lead();

        l.FirstName = 'usuario';
        l.LastName = 'prueba';
        l.Numero_de_celular__c = '3214567890';
        l.Email = 'correo@example.com';
        l.Numero_de_identificacion__c = '7896504';
        l.Canal_digital__c ='Si';
        l.Status = 'Nuevo';
        l.Puntaje_data_credito__c = 780;
        l.Concepto_del_candidato__c = 'Cumple score';
        
        insert l;
    }
}