src/objects/Paz_y_salvo__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Paz y salvos</relationshipLabel>
        <relationshipName>Paz_y_salvos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Paz y salvos (Codeudor 1)</relationshipLabel>
        <relationshipName>Paz_y_salvos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Paz y salvos (Codeudor 2)</relationshipLabel>
        <relationshipName>Paz_y_salvos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Paz y salvos (Codeudor 3)</relationshipLabel>
        <relationshipName>Paz_y_salvos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Credito__c</fullName>
        <externalId>true</externalId>
        <label>Solicitud de credito no</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Paz y salvos</relationshipLabel>
        <relationshipName>Paz_y_salvos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Credito__c</fullName>
        <externalId>true</externalId>
        <label>Id Crédito</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paz_y_salvo__c</fullName>
        <label>Paz y salvo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/PazYSalvos_cls.cls
public with sharing class PazYSalvos_cls {
	
	public void actualizarCodeudores(Paz_y_salvo__c objActual)
	{
		List<Solicitud_de_credito__c> lstSolicitud = [SELECT Name, Cliente_deudor__c,Codeudor_1__c,Codeudor_2__c,Codeudor_3__c FROM Solicitud_de_credito__c WHERE Id =: objActual.Solicitud_de_credito__c ];
		if( !lstSolicitud.isEmpty() )
		{
			objActual.Cliente_deudor__c = lstSolicitud.get(0).Cliente_deudor__c;
			if(lstSolicitud.get(0).Codeudor_1__c != null)
			{
				objActual.Codeudor_1__c = lstSolicitud.get(0).Codeudor_1__c;
			}
			if(lstSolicitud.get(0).Codeudor_2__c != null)
			{
				objActual.Codeudor_2__c = lstSolicitud.get(0).Codeudor_2__c;
			}
			if(lstSolicitud.get(0).Codeudor_3__c != null)
			{
				objActual.Codeudor_3__c = lstSolicitud.get(0).Codeudor_3__c;
			}
			objActual.Id_Credito__c = lstSolicitud.get(0).Name;
		}
	}
}