src/objects/Proyecto__c.object
<CustomObject>
    <description>Permite identificar la información de proyectos que pertenecen a cada constructora</description>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre de Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fecha_comite__c</fullName>
        <label>Fecha comité</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proyecto__c</fullName>
        <label>Proyecto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valor_del_credito__c</fullName>
        <label>Valor del crédito</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/CartaController.cls
public with sharing class CartaController {
    
    public String Banco {get; set;}
    public String Nit {get; set;}
    public String valor {get; set;}
    public Id solicitudDeCredito {get; set;}
    public Date fechaDeAprobacion {get; set;}
	public String deudorPrincipal {get; set;}
	public String direccionDelInmueble {get; set;}
	public String proyecto {get; set;}
	public String matricula {get; set;}
	
	public CartaController(){
		this.Banco = 'Caja Social';
		this.Nit = '98754321-3';
		this.solicitudDeCredito = ApexPages.currentPage().getParameters().get('id');
		Solicitud_de_credito__c sc = [select 
			Id,
			Valor_del_credito__c, 
			Fecha_comite__c, 
			Cliente_deudor__c, 
			Proyecto__c 
			from Solicitud_de_credito__c where Id = :this.solicitudDeCredito];
			
		System.debug(sc);
		
	}
}