src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Radicacion__c</fullName>
        <externalId>true</externalId>
        <label>Id Radicación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicitud_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solicitud de crédito</label>
        <referenceTo>Solicitud_de_credito__c</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Solicitud_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solicitudes de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Solicitudes_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/RadicacionCredito_ctr.cls
public class RadicacionCredito_ctr {
	public ApexPages.Standardcontroller controller {get;set;}
    public Radicacion_de_credito__c recordRadicacion  {get;set;}
    public Solicitud_de_credito__c recordSolicitud {get;set;}
    
    public RadicacionCredito_ctr()
    {
    	
    }
    
    //Método constructor de la clase
    public RadicacionCredito_ctr(ApexPages.Standardcontroller incontroller)
    {
    	recordSolicitud = new Solicitud_de_credito__c();
        recordRadicacion = (Radicacion_de_credito__c)incontroller.getRecord();
        System.debug( 'Radicación en el constructor --> '+recordRadicacion );
        List<Solicitud_de_credito__c> lstSC = [SELECT Name, Cliente_deudor__c,Codeudor_1__c,Codeudor_2__c,Codeudor_3__c FROM Solicitud_de_credito__c WHERE Id =:recordRadicacion.Solicitud_de_credito__c];
        if(!lstSC.isEmpty())
        {
        	recordSolicitud = lstSC.get(0);
        	recordRadicacion.Cliente_deudor__c = lstSC.get(0).Cliente_deudor__c;
        	if(lstSC.get(0).Codeudor_1__c != null)
        	{
        		recordRadicacion.Codeudor_1__c = lstSC.get(0).Codeudor_1__c;
        	}
        	if(lstSC.get(0).Codeudor_2__c != null)
        	{
        		recordRadicacion.Codeudor_2__c = lstSC.get(0).Codeudor_2__c;
        	}
        	if(lstSC.get(0).Codeudor_3__c != null)
        	{
        		recordRadicacion.Codeudor_3__c = lstSC.get(0).Codeudor_3__c;
        	}
        	recordRadicacion.Id_Radicacion__c = recordRadicacion.Name;
        }
    }
    
    //Método que se encarga de actualizar el registro de cuenta y direccionar hacia la cuenta
    public PageReference guardar()
    {
    	System.debug( 'Radicación desde el boton guardar '+recordRadicacion );
    	insert recordRadicacion;
        PageReference pr;
        pr = new PageReference('/' + recordRadicacion.id);
        pr.setRedirect(true);
        return pr;
    }
    
    public PageReference cancelar()
    {	
        PageReference pr;
        pr = new PageReference('/' + recordRadicacion.Solicitud_de_credito__c);
        pr.setRedirect(true);
        return pr;
    }
}