src/objects/Radicacion_de_credito__c.object
<CustomObject>
    <fields>
        <fullName>Cargo_actual__c</fullName>
        <label>Cargo actual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cargo_deudor__c</fullName>
        <label>Cargo deudor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 1)</relationshipLabel>
        <relationshipName>Radicaciones_de_cr_ditos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 2)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Radicaciones de créditos (Codeudor 3)</relationshipLabel>
        <relationshipName>Radicaciones_de_creditos3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Radicacion__c</fullName>
        <externalId>true</externalId>
        <label>Id Radicación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Referenciacion_y_verificacion__c.object
<CustomObject>
    <description>Identifica la información de los solicitantes para realizar el proceso de referenciación y verificación</description>
    <fields>
        <fullName>Cargo_deudor__c</fullName>
        <label>Cargo deudor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cliente_deudor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente deudor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones (Codeudor 1)</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones (Codeudor 2)</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codeudor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codeudor 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones (Codeudor 3)</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Radicacion__c</fullName>
        <label>Id Radicación</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radicacion_de_credito__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Radicación de crédito</label>
        <referenceTo>Radicacion_de_credito__c</referenceTo>
        <relationshipLabel>Referenciaciones y verificaciones</relationshipLabel>
        <relationshipName>Referenciaciones_y_verificaciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referenciación y verificación</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Consecutivo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referenciaciones y verificaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReferenciacionVerificacion_cls.cls
public with sharing class ReferenciacionVerificacion_cls 
{
	public ReferenciacionVerificacion_cls()
	{
		
	}
	public void actualizarCodeudores(Referenciacion_y_verificacion__c referenciacionActual)
	{
		List<Radicacion_de_credito__c> lstRadicacion = [SELECT Name, Cargo_actual__c, Cliente_deudor__c,Codeudor_1__c,Codeudor_2__c,Codeudor_3__c FROM Radicacion_de_credito__c WHERE Id =:referenciacionActual.Radicacion_de_credito__c];
		if( !lstRadicacion.isEmpty() )
		{
			referenciacionActual.Cliente_deudor__c = lstRadicacion.get(0).Cliente_deudor__c;
			if(lstRadicacion.get(0).Codeudor_1__c != null)
			{
				referenciacionActual.Codeudor_1__c = lstRadicacion.get(0).Codeudor_1__c;
			}
			if(lstRadicacion.get(0).Codeudor_2__c != null)
			{
				referenciacionActual.Codeudor_2__c = lstRadicacion.get(0).Codeudor_2__c;
			}
			if(lstRadicacion.get(0).Codeudor_3__c != null)
			{
				referenciacionActual.Codeudor_3__c = lstRadicacion.get(0).Codeudor_3__c;
			}
			referenciacionActual.Id_Radicacion__c = lstRadicacion.get(0).Name;
			//referenciacionActual.Cargo_deudor__c = lstRadicacion.get(0).Cargo_actual__c;
		}
	}
}